theme = "autumn"

[editor]
color-modes = true


[keys.normal]
C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-g = [
  ':write-all',
  ':insert-output lazygit >/dev/tty',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':redraw',
  ':reload-all',
]
C-p = [
  ':insert-output gh dash >/dev/tty',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':redraw',
]
[keys.normal."\\"]
m = [
  ':write',
  ':insert-output COLORTERM=truecolor TERM=xterm-256color glow -p -s dark -w 100 %{buffer_name} >/dev/tty </dev/tty',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':redraw',
]

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
