vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "screenshot_theme"
vim.o.background = "dark"

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local bg        = "#0d1117"
local bg2       = "#161b22"
local fg        = "#cdd9e5"
local comment   = "#4a5568"
local pink      = "#f92672"
local cyan      = "#79d4d5"
local green     = "#a8d8a8"
local orange    = "#e07c54"
local white     = "#e8edf3"
local red       = "#f07178"

hi("Normal",        { fg = fg,      bg = bg })
hi("NormalFloat",   { fg = fg,      bg = bg2 })
hi("LineNr",        { fg = comment, bg = bg })
hi("CursorLine",    { bg = bg2 })
hi("CursorLineNr",  { fg = white,   bg = bg2, bold = true })
hi("SignColumn",    { bg = bg })
hi("ColorColumn",   { bg = bg2 })
hi("VertSplit",     { fg = bg2,     bg = bg })
hi("WinSeparator",  { fg = bg2,     bg = bg })
hi("StatusLine",    { fg = fg,      bg = bg2 })
hi("StatusLineNC",  { fg = comment, bg = bg })
hi("Pmenu",         { fg = fg,      bg = bg2 })
hi("PmenuSel",      { fg = bg,      bg = cyan })
hi("PmenuSbar",     { bg = bg2 })
hi("PmenuThumb",    { bg = comment })
hi("MatchParen",    { fg = orange,  bold = true, underline = true })
hi("Search",        { fg = bg,      bg = orange })
hi("IncSearch",     { fg = bg,      bg = pink })
hi("Visual",        { bg = "#1e2d3d" })
hi("NonText",       { fg = comment })
hi("EndOfBuffer",   { fg = bg })
hi("Folded",        { fg = comment, bg = bg2 })
hi("FoldColumn",    { fg = comment, bg = bg })

hi("Comment",       { fg = comment, italic = true })
hi("Constant",      { fg = orange })
hi("String",        { fg = green })
hi("Character",     { fg = green })
hi("Number",        { fg = orange })
hi("Float",         { fg = orange })
hi("Boolean",       { fg = orange })
hi("Identifier",    { fg = white })
hi("Function",      { fg = green })
hi("Statement",     { fg = pink })
hi("Keyword",       { fg = pink })
hi("Conditional",   { fg = pink })
hi("Repeat",        { fg = pink })
hi("Label",         { fg = pink })
hi("Operator",      { fg = white })
hi("Exception",     { fg = pink })
hi("PreProc",       { fg = cyan })
hi("Include",       { fg = pink })
hi("Define",        { fg = pink })
hi("Macro",         { fg = cyan })
hi("Type",          { fg = cyan })
hi("StorageClass",  { fg = pink })
hi("Structure",     { fg = cyan })
hi("Typedef",       { fg = cyan })
hi("Special",       { fg = orange })
hi("SpecialChar",   { fg = orange })
hi("Delimiter",     { fg = white })
hi("Underlined",    { underline = true })
hi("Error",         { fg = red })
hi("Todo",          { fg = bg, bg = orange, bold = true })

hi("@keyword",               { fg = pink })
hi("@keyword.function",      { fg = pink })
hi("@keyword.return",        { fg = pink })
hi("@keyword.operator",      { fg = pink })
hi("@conditional",           { fg = pink })
hi("@repeat",                { fg = pink })
hi("@type",                  { fg = cyan })
hi("@type.builtin",          { fg = cyan })
hi("@type.qualifier",        { fg = pink })
hi("@storageclass",          { fg = pink })
hi("@function",              { fg = green })
hi("@function.call",         { fg = green })
hi("@method",                { fg = green })
hi("@method.call",           { fg = green })
hi("@namespace",             { fg = cyan })
hi("@variable",              { fg = white })
hi("@variable.builtin",      { fg = orange })
hi("@parameter",             { fg = white })
hi("@field",                 { fg = white })
hi("@property",              { fg = white })
hi("@number",                { fg = orange })
hi("@float",                 { fg = orange })
hi("@boolean",               { fg = orange })
hi("@string",                { fg = green })
hi("@comment",               { fg = comment, italic = true })
hi("@operator",              { fg = white })
hi("@punctuation",           { fg = white })
hi("@punctuation.bracket",   { fg = white })
hi("@punctuation.delimiter", { fg = white })
hi("@constructor",           { fg = cyan })
hi("@constant",              { fg = orange })
hi("@constant.builtin",      { fg = orange })

hi("DiagnosticError",           { fg = red })
hi("DiagnosticWarn",            { fg = orange })
hi("DiagnosticInfo",            { fg = cyan })
hi("DiagnosticHint",            { fg = comment })
hi("DiagnosticUnderlineError",  { undercurl = true, sp = red })
hi("DiagnosticUnderlineWarn",   { undercurl = true, sp = orange })

hi("GitSignsAdd",     { fg = green })
hi("GitSignsChange",  { fg = orange })
hi("GitSignsDelete",  { fg = red })
